productPage:
  - hero:
    - image: /assests/image/hero.png #???
    - descrption: Hero description
  - journey Cards:
      - journeyCard:
        - title: Learn
        - description: 'Use our AI-powered portal to quickly discover the right integration for your next app project.
        
        Experiment with our API’s in our intelligent API Explorer. 
        
        Browse sample code and follow our guided tutorials to learn best practices for integration.'
        - link: 
          - type: markdown
          - uri: /docs/learn.md
        - contextualNavigationCards: #cnav card
          - contextualNavigationCard:
            - title: Getting Started
            - description: Learn how to integrate with Open Banking.
            - link: 
              - type: markdown
              - uri: /docs/getting-started.md
          - contextualNavigationCard:
            - title: Tutorials
            - description: Let's tut!
            - link: 
              - type: markdown
              - uri: /docs/tutorials.md
          - contextualNavigationCard:
            - title: Video
            - description: Watch
            - link: 
              - type: externalLink # [externalLink | internalLink | markdown]
              - uri: https://www.youtube.com/watch?v=bm8gePjIWQM
      - journeyCard:
        - title: Build
        - description: 'Build on top of our sample code to get your app coded in minutes.
        
        Our lightweight SDK’s and plug-in’s might be the fastest path to completing your app.'
        - link: 
          - type: markdown
          - uri: /docs/build.md
        - contextualNavigationCards:
          - contextualNavigationCard:
            - title: SDKs
            - description: Use SDKs to accelarate your development
            - link: 
              - type: markdown
              - uri: /docs/sdks.md
          - contextualNavigationCard:
            - title: APIs
            - description: Explore all our APIs
            - cardType: reference | page
            - link: 
              - type: internalLink
              - uri: /docs/api # => http://dev.fiserv.com/docs/api
